name: auto-download-bq

on:
  schedule:
    - cron: "55 * * * *"   # UTC 기준 매시 55분
  workflow_dispatch:

concurrency:
  group: auto-download-bq-${{ github.ref }}
  cancel-in-progress: false  # 새 실행이 와도 이전 실행을 취소하지 않음(원하면 true)

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 90
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Restore GCP creds file
        env:
          SERVICE_ACCOUNT_JSON_B64: ${{ secrets.SERVICE_ACCOUNT_JSON_B64 }}
        run: |
          echo "$SERVICE_ACCOUNT_JSON_B64" | base64 -d > bigquery-credentials.json

      - name: Run script
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/bigquery-credentials.json
          LOGIN_ID: ${{ secrets.LOGIN_ID }}
          LOGIN_PW: ${{ secrets.LOGIN_PW }}
          GCP_PROJECT: ${{ secrets.GCP_PROJECT }}
          BQ_DATASET: ${{ secrets.BQ_DATASET }}   # ← 점 표기
          BQ_TABLE: ${{ secrets.BQ_TABLE }}       # ← 점 표기
        run: python auto_download_headless_log.py

      - name: Upload logs/artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: run-artifacts
          path: |
            log.txt
            downloads/**
            *.png
            *.jpg
