name: auto-download-bq

on:
  schedule:
    - cron: "55 * * * *"   # KST에서도 매시 55분에 실행됨 (분은 UTC와 동일)
  workflow_dispatch:

concurrency:
  group: auto-download-bq
  cancel-in-progress: true   # 새 실행이 오면 이전 실행 취소

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 15      # (선택) 과도한 대기/실행 방지
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Restore GCP creds file
        env:
          SERVICE_ACCOUNT_JSON_B64: ${{ secrets.SERVICE_ACCOUNT_JSON_B64 }}
        run: |
          echo "$SERVICE_ACCOUNT_JSON_B64" | base64 -d > bigquery-credentials.json

      - name: Run script
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/bigquery-credentials.json
          LOGIN_ID: ${{ secrets.LOGIN_ID }}
          LOGIN_PW: ${{ secrets.LOGIN_PW }}
          GCP_PROJECT: ${{ secrets.GCP_PROJECT }}
          BQ_DATASET: ${{ secrets.BQ_DATASET }}
          BQ_TABLE: ${{ secrets.BQ_TABLE }}
        run: python auto_download_headless_log.py
